// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class AuctionSession
{
    public Guid Id { get; set; }

    public Guid AuctionItemId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public decimal? FinalPrice { get; set; }

    public bool? IsEnded { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<AuctionBid> AuctionBids { get; set; } = new List<AuctionBid>();

    public virtual AuctionItem AuctionItem { get; set; }
}