// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class AuctionItem
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public string Condition { get; set; }

    public decimal? StartPrice { get; set; }

    public decimal? StepPrice { get; set; }

    public decimal? ReservePrice { get; set; }

    public int? Status { get; set; }

    public string StaffNote { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<AuctionSession> AuctionSessions { get; set; } = new List<AuctionSession>();

    public virtual Account User { get; set; }
}