// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class AuctionShippingInfo
{
    public Guid Id { get; set; }

    public Guid AuctionSessionId { get; set; }

    public Guid UserId { get; set; }

    public string Address { get; set; }

    public DateTime ConfirmedAt { get; set; }

    public virtual AuctionSession AuctionSession { get; set; }

    public virtual Account User { get; set; }
}