// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class EmailToken
{
    public Guid Id { get; set; }

    public Guid AccountId { get; set; }

    public string Token { get; set; }

    public string TokenType { get; set; }

    public DateTime ExpiryDate { get; set; }

    public bool? IsUsed { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Account Account { get; set; }
}