// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class Order
{
    public Guid Id { get; set; }

    public Guid? CartId { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? ShippingCost { get; set; }

    public Guid? VoucherId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    public virtual Transaction Transaction { get; set; }

    public virtual Voucher Voucher { get; set; }
}