// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class ProductSet
{
    public Guid Id { get; set; }

    public string ProductSetName { get; set; }

    public string Description { get; set; }

    public int? SetQuantity { get; set; }

    public int? Quantity { get; set; }

    public decimal? Price { get; set; }

    public Guid? PromotionId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public Guid? ProductId { get; set; }

    public virtual ICollection<CartProduct> CartProducts { get; set; } = new List<CartProduct>();

    public virtual Product Product { get; set; }

    public virtual Promotion Promotion { get; set; }
}