// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class Product
{
    public Guid Id { get; set; }

    public string ProductName { get; set; }

    public string Description { get; set; }

    public int? Quantity { get; set; }

    public decimal Price { get; set; }

    public Guid? ManufacturerId { get; set; }

    public Guid? ProductSetId { get; set; }

    public Guid? PromotionId { get; set; }

    public Guid? CategoryId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<CartProduct> CartProducts { get; set; } = new List<CartProduct>();

    public virtual Category Category { get; set; }

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    public virtual Manufacturer Manufacturer { get; set; }

    public virtual ProductSet ProductSet { get; set; }

    public virtual Promotion Promotion { get; set; }
}