// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class ShipmentHistory
{
    public Guid Id { get; set; }

    public Guid? ShipmentStatusId { get; set; }

    public Guid? ShipmentId { get; set; }

    public Guid? AccountId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Account Account { get; set; }

    public virtual Shipment Shipment { get; set; }

    public virtual ShipmentStatus ShipmentStatus { get; set; }
}