// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class SpinHistory
{
    public Guid Id { get; set; }

    public Guid AccountId { get; set; }

    public Guid SpinWheelId { get; set; }

    public Guid SpinItemId { get; set; }

    public decimal PricePaid { get; set; }

    public decimal RewardValue { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual SpinItem SpinItem { get; set; }

    public virtual SpinWheel SpinWheel { get; set; }
}