// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RandoX.Data.Entities;

public partial class SpinItem
{
    public Guid Id { get; set; }

    public Guid SpinWheelId { get; set; }

    public string RewardName { get; set; }

    public string RewardType { get; set; }

    public Guid? ProductId { get; set; }

    public Guid? VoucherId { get; set; }

    public decimal RewardValue { get; set; }

    public string ImageUrl { get; set; }

    public decimal Probability { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<SpinHistory> SpinHistories { get; set; } = new List<SpinHistory>();

    public virtual SpinWheel SpinWheel { get; set; }

    public virtual Voucher Voucher { get; set; }
}